[package]
name = "cfdkim"
version = "0.1.2"
authors = ["Sven Sauleau <sven@cloudflare.com>"]
edition = "2021"
description = "DKIM (RFC6376) implementation"
repository = "https://github.com/cloudflare/dkim"
documentation = "https://docs.rs/cfdkim"
categories = ["email"]
keywords = ["email", "dkim", "authentification"]
readme = "README.md"
license = "MIT"

[dependencies]
mailparse = "0.13.7"
quick-error = "2.0.1"
nom = "7.1.0"
chrono = "0.4.19"
trust-dns-resolver = "0.20.3"
futures = "0.3.18"
sha-1 = "0.9"
sha2 = "0.9"
base64 = "0.13.0"
rsa = "0.5.0"
slog = "2.7.0"
indexmap = "1.8.0"

[dev-dependencies]
tokio = { version = "1.18.5", features = ["macros"] }
regex = "1"
